apiVersion: v1
kind: Template
metadata:
  name: "redexporter"
  annotations:
    openshift.io/display-name: "Redmine's metrics exporter application for Prometheus"
    description: "Redmine's metrics exporter Template"
    tags: "redmine, devops"
objects:
- kind: Secret
  apiVersion: v1
  metadata:
    name: ${DC_NAME}-secret
  type: Opaque
  stringData:
    REDMINE_URL: ${REDMINE_URL}
    REDMINE_USER: ${REDMINE_USER}
    REDMINE_PASSWORD: ${REDMINE_PASSWORD}
- kind: DeploymentConfig
  apiVersion: apps.openshift.io/v1
  metadata:
    labels:
      app: redexporter
    name: redexporter
  spec:
    replicas: 1
    selector:
      app: redexporter
      deploymentconfig: ${DC_NAME}
    strategy:
      type: Rolling
    template:
      metadata:
        labels:
          app: redexporter
          deploymentconfig: ${DC_NAME}
      spec:
        containers:
        - name: redexporter
          image: gmh501/redexporter
          imagePullPolicy: Always
          envFrom:
          - secretRef:
              name: ${DC_NAME}-secret
          ports:
          - containerPort: 8080
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
- apiVersion: v1
  kind: Service
  metadata:
    name: ${DC_NAME}
    labels:
      app: redexporter
  spec:
    ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      name: app
    selector:
      deploymentconfig: ${DC_NAME}
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    name: ${DC_NAME}
    labels:
      app: redexporter
  spec:
    port:
      targetPort: 8080
    to:
      kind: Service
      name: ${DC_NAME}
parameters:
- name: DC_NAME
  description: Redexporter DeploymentConfig name
  value: redexporter
- name: REDMINE_URL
  description: Redmine application URL
- name: REDMINE_USER
  description: Redmine application username
- name: REDMINE_PASSWORD
  description: Redmine application password